# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wphase', '0003_auto_20150612_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.CharField(max_length=10)),
                ('code_version', models.IntegerField()),
                ('W_Mrr', models.DecimalField(max_digits=14, decimal_places=6)),
                ('W_Mtt', models.DecimalField(max_digits=14, decimal_places=6)),
                ('W_Mrt', models.DecimalField(max_digits=14, decimal_places=6)),
                ('W_Mrp', models.DecimalField(max_digits=14, decimal_places=6)),
                ('W_Mtp', models.DecimalField(max_digits=14, decimal_places=6)),
                ('W_time_shift', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_half_duration', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_latitude', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_longitude', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_depth', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_M0', models.DecimalField(max_digits=12, decimal_places=2)),
                ('W_Mw', models.DecimalField(max_digits=7, decimal_places=2)),
                ('DC_FLAG', models.BooleanField()),
                ('W_NP1_strike', models.DecimalField(max_digits=7, decimal_places=1)),
                ('W_NP1_dip', models.DecimalField(max_digits=7, decimal_places=1)),
                ('W_NP1_rake', models.DecimalField(max_digits=7, decimal_places=1)),
                ('W_NP2_strike', models.DecimalField(max_digits=7, decimal_places=1)),
                ('W_NP2_dip', models.DecimalField(max_digits=7, decimal_places=1)),
                ('W_NP2_rake', models.DecimalField(max_digits=7, decimal_places=1)),
                ('M_eig1', models.DecimalField(max_digits=14, decimal_places=4)),
                ('M_eig2', models.DecimalField(max_digits=14, decimal_places=4)),
                ('M_eig3', models.DecimalField(max_digits=14, decimal_places=4)),
                ('R_Mrr', models.DecimalField(max_digits=14, decimal_places=6)),
                ('R_Mtt', models.DecimalField(max_digits=14, decimal_places=6)),
                ('R_Mrt', models.DecimalField(max_digits=14, decimal_places=6)),
                ('R_Mrp', models.DecimalField(max_digits=14, decimal_places=6)),
                ('R_Mtp', models.DecimalField(max_digits=14, decimal_places=6)),
                ('R_time_shift', models.DecimalField(max_digits=8, decimal_places=2)),
                ('R_half_duration', models.DecimalField(max_digits=8, decimal_places=2)),
                ('R_latitude', models.DecimalField(max_digits=8, decimal_places=2)),
                ('R_longitude', models.DecimalField(max_digits=8, decimal_places=2)),
                ('R_depth', models.DecimalField(max_digits=8, decimal_places=2)),
                ('R_M0', models.DecimalField(max_digits=12, decimal_places=2)),
                ('R_Mw', models.DecimalField(max_digits=7, decimal_places=2)),
                ('R_NP1_strike', models.DecimalField(max_digits=7, decimal_places=1)),
                ('R_NP1_dip', models.DecimalField(max_digits=7, decimal_places=1)),
                ('R_NP1_rake', models.DecimalField(max_digits=7, decimal_places=1)),
                ('R_NP2_strike', models.DecimalField(max_digits=7, decimal_places=1)),
                ('R_NP2_dip', models.DecimalField(max_digits=7, decimal_places=1)),
                ('R_NP2_rake', models.DecimalField(max_digits=7, decimal_places=1)),
                ('R_eig1', models.DecimalField(max_digits=14, decimal_places=4)),
                ('R_eig2', models.DecimalField(max_digits=14, decimal_places=4)),
                ('R_eig3', models.DecimalField(max_digits=14, decimal_places=4)),
                ('filt_order', models.IntegerField()),
                ('filt_cf1', models.DecimalField(max_digits=7, decimal_places=5)),
                ('filt_cf2', models.DecimalField(max_digits=7, decimal_places=5)),
                ('filt_pass', models.IntegerField()),
                ('med_val', models.DecimalField(max_digits=15, decimal_places=8)),
                ('p2p_med', models.DecimalField(max_digits=15, decimal_places=8)),
                ('p2p_min', models.DecimalField(max_digits=15, decimal_places=8)),
                ('p2p_max', models.DecimalField(max_digits=15, decimal_places=8)),
                ('average', models.DecimalField(max_digits=15, decimal_places=8)),
                ('nb_stations', models.IntegerField()),
                ('nb_channels', models.IntegerField()),
                ('nb_rejected_channels', models.IntegerField()),
                ('stations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('WPWIN', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(max_digits=8, decimal_places=2), size=None)),
                ('Dmin', models.DecimalField(max_digits=8, decimal_places=2)),
                ('Dmax', models.DecimalField(max_digits=8, decimal_places=2)),
                ('wN', models.DecimalField(max_digits=8, decimal_places=2)),
                ('wE', models.DecimalField(max_digits=8, decimal_places=2)),
                ('wZ', models.DecimalField(max_digits=8, decimal_places=2)),
                ('command_line', models.CharField(max_length=50)),
                ('ref_solution', models.CharField(max_length=20)),
                ('cond_thre', models.DecimalField(max_digits=8, decimal_places=3)),
                ('damp_fac', models.DecimalField(max_digits=8, decimal_places=3)),
                ('WRMS', models.DecimalField(max_digits=9, decimal_places=5)),
                ('WRMS_r', models.DecimalField(max_digits=9, decimal_places=5)),
                ('Gap', models.DecimalField(max_digits=5, decimal_places=1)),
                ('Cond_number', models.DecimalField(max_digits=10, decimal_places=1)),
                ('RRMS', models.DecimalField(max_digits=9, decimal_places=5)),
                ('RRMS_r', models.DecimalField(max_digits=9, decimal_places=5)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='event',
            field=models.ForeignKey(to='wphase.Event'),
        ),
    ]
