# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wphase', '0007_event_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='Cond_number',
            new_name='cond_number',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='DC_FLAG',
            new_name='dc_flag',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='Dmax',
            new_name='dmax',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='Dmin',
            new_name='dmin',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='Gap',
            new_name='gap',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='M_eig1',
            new_name='m_eig1',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='M_eig2',
            new_name='m_eig2',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='M_eig3',
            new_name='m_eig3',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_depth',
            new_name='r_depth',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_eig1',
            new_name='r_eig1',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_eig2',
            new_name='r_eig2',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_eig3',
            new_name='r_eig3',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_half_duration',
            new_name='r_half_duration',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_latitude',
            new_name='r_latitude',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_longitude',
            new_name='r_longitude',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_M0',
            new_name='r_m0',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_Mrp',
            new_name='r_mrp',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_Mrr',
            new_name='r_mrr',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_Mrt',
            new_name='r_mrt',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_Mtp',
            new_name='r_mtp',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_Mtt',
            new_name='r_mtt',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_Mw',
            new_name='r_mw',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_NP1_dip',
            new_name='r_np1_dip',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_NP1_rake',
            new_name='r_np1_rake',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_NP1_strike',
            new_name='r_np1_strike',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_NP2_dip',
            new_name='r_np2_dip',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_NP2_rake',
            new_name='r_np2_rake',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_NP2_strike',
            new_name='r_np2_strike',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='R_time_shift',
            new_name='r_time_shift',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='RRMS',
            new_name='rrms',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='RRMS_r',
            new_name='rrms_r',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_depth',
            new_name='w_depth',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_half_duration',
            new_name='w_half_duration',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_latitude',
            new_name='w_latitude',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_longitude',
            new_name='w_longitude',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_M0',
            new_name='w_m0',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_Mrp',
            new_name='w_mrp',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_Mrr',
            new_name='w_mrr',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_Mrt',
            new_name='w_mrt',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_Mtp',
            new_name='w_mtp',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_Mtt',
            new_name='w_mtt',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_Mw',
            new_name='w_mw',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_NP1_dip',
            new_name='w_np1_dip',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_NP1_rake',
            new_name='w_np1_rake',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_NP1_strike',
            new_name='w_np1_strike',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_NP2_dip',
            new_name='w_np2_dip',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_NP2_rake',
            new_name='w_np2_rake',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_NP2_strike',
            new_name='w_np2_strike',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='W_time_shift',
            new_name='w_time_shift',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='wE',
            new_name='we',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='wN',
            new_name='wn',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='WPWIN',
            new_name='wpwin',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='WRMS',
            new_name='wrms',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='WRMS_r',
            new_name='wrms_r',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='wZ',
            new_name='wz',
        ),
    ]
