# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wphase', '0022_auto_20150615_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='epi_depth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='epi_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='epi_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='epi_m1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='epi_m2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='cond_number',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='cond_thre',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='damp_fac',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='dmax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='dmin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='filt_cf1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='filt_cf2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='gap',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_depth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_eig1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_eig2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_eig3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_half_duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_mw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_np1_dip',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_np1_rake',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_np1_strike',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_np2_dip',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_np2_rake',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_np2_strike',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='r_time_shift',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='rrms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='rrms_r',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_depth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_eig1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_eig2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_eig3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_half_duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_mw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_np1_dip',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_np1_rake',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_np1_strike',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_np2_dip',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_np2_rake',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_np2_strike',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='w_time_shift',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='we',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='wn',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='wpwin',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='solution',
            name='wrms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='wrms_r',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='wz',
            field=models.FloatField(),
        ),
    ]
